# version: '3.8'
services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    # restart: always damit der Container immer wieder startet, wenn er beendet wird
    # restart: always
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    #   - ./mosquitto/data:/mosquitto/data
    #   - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
    networks:
      - app-network
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - WORKER_PORT=12345
      - CONTAINER_NAME=${HOSTNAME:-default_hostname}
      - WORKER_COUNT=${WORKER_COUNT}
    depends_on:
      - mqtt-broker
    volumes:
      - ./data/rtt_data.json:/app/data/rtt_data.json
      - ./worker.py:/app/worker.py
      - ./matrix.proto:/app/matrix.proto
    networks:
      - app-network
      - grpc-network
    deploy:
      replicas: ${WORKER_COUNT}
      endpoint_mode: dnsrr # erlaubt es, dass der Controller die Worker direkt ansprechen kann
    entrypoint:  ["python", "worker.py"]

  controller:
    build:
      context: .
      dockerfile: Dockerfile.controller
    container_name: controller
    depends_on:
      - worker
    volumes:
      - ./rtts.json:/app/data/rtts.json
      - ./controller.py:/app/controller.py
      - ./matrix.proto:/app/matrix.proto
    networks:
      - app-network
      - grpc-network
    environment:
      - WORKER_COUNT=${WORKER_COUNT}
    entrypoint:  ["python", "controller.py"]

  http_server:
    build:
      context: .
      dockerfile: Dockerfile.http_server
    container_name: http_server
    networks:
      - app-network
    ports:
    # Port 8080 des Hosts wird auf Port 80 des Containers gemappt
      - "8080:80"
    volumes:
      - ./http_server.py:/usr/src/app/http_server.py
    environment:
      - WORKER_COUNT=${WORKER_COUNT}
    entrypoint:  ["python", "http_server.py"]

networks:
  app-network:
    driver: bridge
  grpc-network:
    driver: bridge

