# Eine offizielle Python-Laufzeitumgebung als übergeordnetes Image verwenden
FROM python:3-slim

# Einstellen des Arbeitsverzeichnisses im Container
WORKDIR /app

# Den Inhalt des aktuellen Verzeichnisses in den Container unter / app kopieren
COPY matrix.proto /app

# Port 12345 für die Welt außerhalb dieses Containers verfügbar machen
EXPOSE 12345

# Installiere die Abhängigkeit ping
RUN apt-get update && apt-get install -y iputils-ping && \
    rm -rf /var/lib/apt/lists/*

RUN pip install grpcio grpcio-tools

# Proto datei generieren
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. matrix.proto


# app.py beim Starten des Containers ausführen
CMD ["python", "controller.py"]

