# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: matrix.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'matrix.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmatrix.proto\x12\x06matrix\"M\n\rMatrixRequest\x12\x10\n\x08matrix_a\x18\x01 \x03(\x05\x12\x10\n\x08matrix_b\x18\x02 \x03(\x05\x12\x0b\n\x03row\x18\x03 \x01(\x05\x12\x0b\n\x03\x63ol\x18\x04 \x01(\x05\":\n\x0eMatrixResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x0b\n\x03row\x18\x02 \x01(\x05\x12\x0b\n\x03\x63ol\x18\x03 \x01(\x05\"8\n\x0cStoreRequest\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x0b\n\x03row\x18\x02 \x01(\x05\x12\x0b\n\x03\x63ol\x18\x03 \x01(\x05\"&\n\x13StoreMatrixResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x93\x01\n\rMatrixService\x12@\n\x0f\x43\x61lculateMatrix\x12\x15.matrix.MatrixRequest\x1a\x16.matrix.MatrixResponse\x12@\n\x0bStoreMatrix\x12\x14.matrix.StoreRequest\x1a\x1b.matrix.StoreMatrixResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'matrix_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MATRIXREQUEST']._serialized_start=24
  _globals['_MATRIXREQUEST']._serialized_end=101
  _globals['_MATRIXRESPONSE']._serialized_start=103
  _globals['_MATRIXRESPONSE']._serialized_end=161
  _globals['_STOREREQUEST']._serialized_start=163
  _globals['_STOREREQUEST']._serialized_end=219
  _globals['_STOREMATRIXRESPONSE']._serialized_start=221
  _globals['_STOREMATRIXRESPONSE']._serialized_end=259
  _globals['_MATRIXSERVICE']._serialized_start=262
  _globals['_MATRIXSERVICE']._serialized_end=409
# @@protoc_insertion_point(module_scope)
