# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import matrix_pb2 as matrix__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in matrix_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MatrixServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateMatrix = channel.unary_unary(
                '/matrix.MatrixService/CalculateMatrix',
                request_serializer=matrix__pb2.MatrixRequest.SerializeToString,
                response_deserializer=matrix__pb2.MatrixResponse.FromString,
                _registered_method=True)
        self.StoreMatrix = channel.unary_unary(
                '/matrix.MatrixService/StoreMatrix',
                request_serializer=matrix__pb2.StoreRequest.SerializeToString,
                response_deserializer=matrix__pb2.StoreMatrixResponse.FromString,
                _registered_method=True)


class MatrixServiceServicer(object):
    """Service definition
    """

    def CalculateMatrix(self, request, context):
        """Calculate matrix multiplication of two matrices A and B
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreMatrix(self, request, context):
        """Store the result of matrix multiplication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatrixServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateMatrix': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateMatrix,
                    request_deserializer=matrix__pb2.MatrixRequest.FromString,
                    response_serializer=matrix__pb2.MatrixResponse.SerializeToString,
            ),
            'StoreMatrix': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreMatrix,
                    request_deserializer=matrix__pb2.StoreRequest.FromString,
                    response_serializer=matrix__pb2.StoreMatrixResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'matrix.MatrixService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('matrix.MatrixService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MatrixService(object):
    """Service definition
    """

    @staticmethod
    def CalculateMatrix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/matrix.MatrixService/CalculateMatrix',
            matrix__pb2.MatrixRequest.SerializeToString,
            matrix__pb2.MatrixResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreMatrix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/matrix.MatrixService/StoreMatrix',
            matrix__pb2.StoreRequest.SerializeToString,
            matrix__pb2.StoreMatrixResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
